name: easydev_basics
description: "EasyDev Flutter package with basic widgets."
repository: https://github.com/aspirity-inc/easydev_flutter/tree/main/packages/easydev_basics
issue_tracker: https://github.com/aspirity-inc/easydev_flutter/issues

version: 1.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easydev_theme: ^1.0.0

  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
