name: easydev_forms
description: "EasyDev Flutter package with widgets for constructing forms."
repository: https://github.com/aspirity-inc/easydev_flutter/tree/main/packages/easydev_forms
issue_tracker: https://github.com/aspirity-inc/easydev_flutter/issues


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easydev_theme: ^1.0.0
  easydev_base_ui: ^1.0.0
  easydev_basics: ^1.0.0

  community_material_icon: ^5.9.55

  flutter_svg: ^2.0.7

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter: