name: easydev_base_ui
description: "EasyDev Flutter package with base widgets."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  easydev_theme:
    path: ../easydev_theme

  community_material_icon: ^5.9.55

  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
  fonts:
    - family: EasyDevIcons
      fonts:
      - asset: lib/icons/EasyDevIcons.ttf