/// Flutter icons EasyDevIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EasyDevIcons
///      fonts:
///       - asset: fonts/EasyDevIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class EasyDevIcons {
  EasyDevIcons._();

  static const _kFontFam = 'EasyDevIcons';
  static const _kFontPkg = 'easydev_base_ui';

  static const IconData textArea = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeOpen = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeClose = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
